### ISSUE TITLE
sendfile失败

### ISSUE THREAD

**Issue by tcaac** [CalvinNeo/ATP#1]
直接创建sendfile的demo 运行sendfile和recvfile会报错 错误应该是指针异常的问题  系统是Ubuntu 不知您这边是否有这个问题呢？

**Comment by CalvinNeo** [comment]
唔，你能提供详细的一些信息吗？我明天检查一下。谢谢

**Comment by tcaac** [comment]
我的操作流程是下载代码，然后解压 ，运行make demos
![image](https://user-images.githubusercontent.com/45855692/49955909-eb90f100-ff3e-11e8-8e53-ab7000172da3.png)
然后运行recvfile
![image](https://user-images.githubusercontent.com/45855692/49956091-580bf000-ff3f-11e8-91d2-bbbb47a044c6.png)
最后运行sendfile
![image](https://user-images.githubusercontent.com/45855692/49956125-6e19b080-ff3f-11e8-91cc-31a8a224a61a.png)
有生成core文件
![image](https://user-images.githubusercontent.com/45855692/49956179-8984bb80-ff3f-11e8-80b2-c798352cd256.png)
但我不太会调
![image](https://user-images.githubusercontent.com/45855692/49956328-e2545400-ff3f-11e8-9acd-aa7e4f42e0c6.png)
显示的是没有那个文件和目录，但是in.dat和out.dat我已经重新单独创建了。

**Comment by CalvinNeo** [comment]
你好，我注意到你是单独运行的sendfile和recvfile两个binary，在这种情况下你应该需要附加一些参数，例如`./sendfile -iin.dat`和`./recvfile -oout.dat`。你可以检查test/run_test.py下的一些demo，你还可以在test文件夹对应的cpp文件中看到所有的参数。
此外推荐你先`make run_test`看一下是否还会core。

**Comment by tcaac** [comment]
您好，我尝试了一下加入参数 还是会报错一样的问题。
对于 make run_test 会出现以下问题
![image](https://user-images.githubusercontent.com/45855692/49957748-bcc94980-ff43-11e8-9f47-314492f5997c.png)
我想到一点  关于send 和 recv 的运行是正常的，不知道对您有没有帮助。
实在抱歉，对于这方面不太懂，可能很简单的问题都没有思路来解决，不好意思。

**Comment by CalvinNeo** [comment]
你这个是Python3……我的脚本是Python2

**Comment by tcaac** [comment]
我也发现这个问题了....我在更改 是否还有问题我会回复您的

**Comment by CalvinNeo** [comment]
对了，我看你在bin里面跑sendfile，我建议你在根下面跑，因为in是生成在根下面的

**Comment by tcaac** [comment]
已经全部尝试了一遍，系统改为python2.7了 在根目录下跑的 还是一样的问题。
![image](https://user-images.githubusercontent.com/45855692/49960093-51cf4100-ff4a-11e8-8be2-4e75b7d88122.png)

**Comment by tcaac** [comment]
对了 跑到make run test时候有这样的错误
![image](https://user-images.githubusercontent.com/45855692/49960207-a4a8f880-ff4a-11e8-8cf6-3bc39f269c06.png)

**Comment by tcaac** [comment]
我查了一下 ， 好像这个错误和之后的错误关系不大 ......

**Comment by CalvinNeo** [comment]
你好，Broken pipe的话我记得出现场景较多的情况是没有找到对应的可执行文件。你check一下有没有生成对应的binary
此外，我刚才在Ubuntu 16.04测试了一下是没有问题的。我的命令行是（全部在根目录下）
```
make
python test/makedata.py # 这一步是为了生成in.dat
./bin/recvfile -oout.dat
./bin/sendfile -iin.dat # 你需要在另一个中断窗口执行
```

**Comment by tcaac** [comment]
我这边还是不行 那我再调试吧

**Comment by CalvinNeo** [comment]
好吧，要是你方便的话可以把你的整个环境打包给calvinneo@calvinneo.com，我有空研究下

**Comment by tcaac** [comment]
嗯嗯 有时间的话我研究一下怎么打包
